# Generated by Django 3.1 on 2022-05-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonVeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nvImage', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='veg',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
